### ISSUE TITLE
[feat] Add ChatGPT to the bot

### ISSUE THREAD

**Issue by simonhyll** [tauri-apps/tauri-discord-bot#109]
The idea is fairly simple. Either as a command or as a reaction in the support message we send (once that feature is merged) to trigger a function that sends the full chat log in the thread to ChatGPT to offer support. I've tried it several times and by literally just copy-pasting a bunch of the issues in the support channel to ChatGPT it can provide quite useful support. Not always, but it's better than what a lot of users provide.

The feature will require a subscription to ChatGPT.

The only potential issue I see with this is if there's some legal consideration with sharing the chat log with a third party. When I've done it myself I've just taken the initial message and only when there's no sensitive information in there. I think I can quite easily make it so that the bot either A) requests explicit permission before sending everything in the thread that only the user himself has written (or anyone has written if we just add some disclaimers here and there in writing), or B) open a dialog where the user can manually provide additional information (such as the contents of other peoples messages) which also informs the user that the data will be sent to a third party service for analysis.

This feature isn't just a way of giving people faster support, but it's also easier to provide support if we get some extra input from ChatGPT. Not all users provide sufficient information for us to figure out what's wrong, which is where ChatGPT sometimes actually has some pretty good clues as to what might be wrong, and if it doesn't figure out the solution when the user chats with ChatGPT via the Tauri Bot, they can at least cover the basics and give us more to go on.

I see this as kind of a supplement to users providing `tauri info`. If I could I would force all users to first send their issue to ChatGPT just to see if they can solve it themselves. Don't give a man a fish, give him an artificial intelligence that sometimes provides helpful hints as to how he can catch a fish.

**Comment by FabianLars** [comment]
I am heavily heavily against this idea. Please don't. Chatgpt tends to do more harm than good in the context of tauri apps.

Everytime someone asks in #support showing chatgpt snippets they're not only outdated but straight up wrong, using apis that _never_ existed in Tauri.

So yes it sounds fun, but for tauri specific stuff it results in more work for us because we constantly have to correct it...

**Comment by lorenzolewis** [comment]
Yeah, correctness of what it generates aside, we're also responsible for what gets posted to the Discord server, the website, etc. It's a similar issue that I have with embedding GitHub discussions directly on blog posts on the website. If you get spam there or inappropriate content then we're responsible for it as Tauri (so instead we link out to GitHub). 

Now there's an alternative to this I think we briefly talked about before. That's having the bot parse the website (via the search API) and returning search results directly in Discord as a gentle suggestion. We improve that by improving the docs (and hopefully it would gently force us to put more in the docs in terms of FAQs, SEO, etc.)

**Comment by simonhyll** [comment]
Having played around more with ChatGPT, while I feel it could be a cool feature, I can agree that due to character limitations in adding history to a prompt, and the limit to the amount of characters returned, there's just no way this can be made in any other way than actually developing a full on ChatGPT client for the bot, and that's a bit out of the scope of the project, so I'll close this as not planned.
