### ISSUE TITLE
Remove Role Reaction Functionality

### ISSUE THREAD

**Issue by lorenzolewis** [tauri-apps/tauri-discord-bot#126]
Going to be switching over to the built-in Discord community onboarding functionality in the coming weeks. I think we should keep the current message the bot posts in `#rules` but remove the server roles section and the reaction functionality instead. If it's possible in that intro message to link to the "Channels & Roles" tab in Discord then it's be cool to add that to the end of the message to give a bit of visibility (but no biggie if not)

**Comment by simonhyll** [comment]
Forgot to close this issue after my PR was merged 😅
